Implemented locationBias and locationRestriction for IOS
matanshukry/flutter_google_places_sdk pull request #20
Opened 2022-08-01 08:57 UTC by erdnj

### Implemented locationBias and locationRestriction for IOS to solve #19 
* Also increased version numbers and updated changelog regarding to conventions.
* It is ready to release.

2022-08-04 19:13 UTC, erdnj commented
@matanshukry @sidneyorlovski @ogustavobelociandt could someone review this PR ?

2022-08-04 20:04 UTC, matanshukry requested changes

2022-08-04 20:04 UTC, matanshukry commented on flutter_google_places_sdk/pubspec.yaml
> +  flutter_google_places_sdk_ios: ^0.1.2+2
don't do this. I know it's annoying, but I'm tagging each published version - so we can't make a single commit upgrading the version for the main package `flutter_google_places_sdk` together with the ios package `flutter_google_places_sdk_ios` - we need 2 different commits for that.

2022-08-15 08:39 UTC, erdnj commented on flutter_google_places_sdk/pubspec.yaml
> +  flutter_google_places_sdk_ios: ^0.1.2+2
I have removed my edits on main package to version update as you said.

2022-08-18 12:50 UTC, erdnj commented
@matanshukry, is this version okey to your convention ? I just bump the iOS version.

2022-12-10 08:49 UTC, matanshukry approved these changes

2022-12-10 08:49 UTC, merged

2022-12-10 08:53 UTC, matanshukry commented
@erdnj I apologize for the delay.
I have merged the package and published a new ios version - `0.1.2+2`

2022-12-10 09:02 UTC, erdnj commented
Better late than never. 
Thanks for the package.