fix web: add origin to the AutocompletionRequest
matanshukry/flutter_google_places_sdk pull request #24
Opened 2022-12-02 12:49 UTC by picaoao

- the origin parameter was not being passed to the request, resulting in distance meters not being returned in case we passed it

2022-12-10 08:56 UTC, matanshukry requested changes

2022-12-10 08:56 UTC, matanshukry commented on flutter_google_places_sdk_web/pubspec.yaml
> +version: 0.1.4+2
it's really a minor fix - please change it to `0.1.3+2`.
This change should be made together with a change to the CHANGELOG file too though.
So either update both or none (and I will update both after).

2023-01-09 12:34 UTC, picaoao commented on flutter_google_places_sdk_web/pubspec.yaml
> +version: 0.1.4+2
@matanshukry 

Sorry for the delay.
Thanks, I've applied the changes.

2023-01-21 08:20 UTC, merged

2023-01-21 08:21 UTC, matanshukry commented
@picaoao sorry for the long delay - merged. Will publish versions soon.